language: ruby

services:
  - postgresql

before_script:
  - psql  -c 'CREATE DATABASE chitter_test;' -U postgres
  - psql  -c 'CREATE TABLE peeps (id SERIAL PRIMARY KEY, message VARCHAR(280));' -U postgres

script:
  - bundle exec rspec
